sudo: required
language: java
jdk:
- openjdk10
- openjdk9
- openjdk8
- openjdk6

matrix:
  allow_failures:
  # https://github.com/square/okhttp/issues/528
  - jdk: openjdk6
notifications:
  slack:
    secure: l3H3EIybvWkrYH2gtMr+fBwndHmpXUcdqixb/h2IDoTf0oJfv3QCSQIWfDZ4vBMMuBHeYpv2Dg8RNhCcg64QVhSf6ZQNYnGb8PAqcVbi+hoaco25pAe/2CpiGFtbfS/PEkl9lo86LDCuxdR2UFR8AEcIdDTPvOMB6JkrX3Uaela/JdC/sbi+8qdxSJmi7SgpcvdlnZScecQ6RXT7cOiJv8WjM+s13cHLcQLu5uHf4kf+WolbQ4fychbz/UsTA/z9O3svwam9P+QfNFfjQcwfvdeQ7t7zj9Wd67GMHCTHIKM8rwdc2OQ6IVvuBgXAL9gn8pxYKq14vK3wbOJvEgD7EEJehfOpnFeGyPKtGs5jGlFQg0bT0fY3QqpHphvpTtz5taLeWpXkEaDws8HmlEeFgiCwz6HuMzHXnhr8dAUIPskaVR+C+G7DSxcAg5isFIObywBH18NrJiKmul7XUdUBjyFKnaQZozoK1IjzITnuuRq66cTSeLdpVC0RvvVPta6jQ0V9kQZDa662Sz3nst0iipgyFuNgJVjwJmjNMkeImxikOerr/zurK+6IVTkZxU2rtFX/4Hht0EObIbq/Fcn49vlfsoMo5HcuuaKJFg7gOrWOTTtDYa4pQRyBCck8pxSQU3giAgqYcYVpanZjWJS76iHHeo0HgPwzRPtO1Gig458=
